# This is a basic workflow to help you get started with Actions

name: Build Docker image after Tag

# Controls when the action will run. 
on:
  # Trigger when pushed
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Triggers the workflow on manual tagging
  release:
    types: [prereleased, published]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build-and-publish-tag"
  build-and-publish-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags

    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish Tag Docker image
      uses: VaultVulp/gp-docker-action@1.1.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: one-night-ultimate-discord # Provide only Docker image name
        extract-git-tag: true # Provide flag to extract Docker image tag from git reference
